### ISSUE TITLE
Error when exporting from Lion King game

### ISSUE THREAD

**Issue by n0samu** [npjg/MediaStation#1]
The below error was encountered when exporting from the [Disney's Animated Storybook: The Lion King](https://archive.org/details/disneys-animated-storybook-the-lion-king-uk) game. I mounted the ISO file as drive D: and ran this command: `python cxt.py "D:\DATA" "G:\Media Station Rips\lionking-export"`.
```
Traceback (most recent call last):
  File "cxt.py", line 1451, in parse
    cxt.parse(stream)
  File "cxt.py", line 1043, in parse
    res = self.get_header(stream, chunk)
  File "cxt.py", line 1177, in get_header
    raise ValueError("Leftover end-of-chunk flags should not be present")
ValueError: Leftover end-of-chunk flags should not be present
```
This error occurred many times and it seems like the export failed entirely. I get only a system.json file without any subfolders or exported assets. [system.zip](https://github.com/npjg/cxt/files/10129043/system.zip)

**Comment by n0samu** [comment]
The same problem also occurs with [Disney's Animated Storybook: Pocahontas](https://archive.org/details/POCAHONTAS_ASB).

**Comment by npjg** [comment]
See my comment on your other issue - I will try to repair this code soon. 😊

**Comment by npjg** [comment]
Finally got around to the re-write that was needed here. Sorry this is so late, but if you're still interested in this project you can install the updated version from PyPI (https://pypi.org/project/MediaStation): `pip install MediaStation`. Then use the installed `MediaStation` script.

**Comment by n0samu** [comment]
Thanks so much, I'll try it soon! 😃

**Comment by npjg** [comment]
Note that Pocahontas ASB export still seems to fail for me, looking into that tonight.
