### ISSUE TITLE
Errors when exporting from 101 Dalmatians game

### ISSUE THREAD

**Issue by n0samu** [npjg/MediaStation#2]
The below errors were encountered when exporting from the [Disney's Animated Storybook: 101 Dalmatians](https://archive.org/details/101DALMATIANS_ASB) game. I mounted the ISO file as drive D: and ran this command: `python cxt.py "D:\DATA" "G:\Media Station Rips\Dalmatians"`.
```
Traceback (most recent call last):
  File "cxt.py", line 1451, in parse
    cxt.parse(stream)
  File "cxt.py", line 1030, in parse
    if not self.get_header(stream, chunk): break
  File "cxt.py", line 1132, in get_header
    contents = [AssetHeader(stream)]
  File "cxt.py", line 577, in __init__
    raise TypeError("AssetHeader(): Unknown field delimiter in header: 0x{:0>4x}".format(type.d))
TypeError: AssetHeader(): Unknown field delimiter in header: 0x0773
```
```
Traceback (most recent call last):
  File "cxt.py", line 1467, in parse
    logging.debug(" >>> {} ".format(header))
  File "cxt.py", line 164, in __format__
    return self.__repr__()
  File "cxt.py", line 608, in __repr__
    self.filenum.d, self.type.d, self.id.d, self.id.d,
AttributeError: 'str' object has no attribute 'd'
```
```
Traceback (most recent call last):
  File "cxt.py", line 1472, in parse
    value_assert(stream.tell(), riff["offset"], "stream position")
  File "cxt.py", line 132, in value_assert
    assert ax == target, msg
AssertionError: Expected stream position 871728 (0xd4d30), received 1150402 (0x118dc2)
```
```
Traceback (most recent call last):
  File "cxt.py", line 1451, in parse
    cxt.parse(stream)
  File "cxt.py", line 1030, in parse
    if not self.get_header(stream, chunk): break
  File "cxt.py", line 1132, in get_header
    contents = [AssetHeader(stream)]
  File "cxt.py", line 600, in __init__
    self.children.append(AssetHeader(stream, stage=True))
  File "cxt.py", line 577, in __init__
    raise TypeError("AssetHeader(): Unknown field delimiter in header: 0x{:0>4x}".format(type.d))
TypeError: AssetHeader(): Unknown field delimiter in header: 0x06ac
```
I received these errors (or variations of them) many times during the export. I've listed the errors in order of first appearance.

And at the very end, this error occurs (which I think is harmless):
```
Traceback (most recent call last):
  File "cxt.py", line 1472, in parse
    value_assert(stream.tell(), riff["offset"], "stream position")
  File "cxt.py", line 132, in value_assert
    assert ax == target, msg
AssertionError: Expected stream position 19414016 (0x1283c00), received 16 (0x0010)
```

Also, many of the images are exported as blank/black PNGs, and it seems like only a small fraction of the assets are exported correctly. I've attached the exported `131` folder as an example: [131.zip](https://github.com/npjg/cxt/files/10128988/131.zip).

The same (or very similar) errors occur when exporting from these other games:
- [Ariel's Story Studio](https://archive.org/details/ArielsStoryStudio)
- [Disney's Animated Storybook: Hercules](https://archive.org/details/HERCULES_ASB)
- [Disney's Animated Storybook: The Hunchback of Notre Dame](https://archive.org/details/HUNCHBACK1996)

**Comment by npjg** [comment]
Thank you for bringing this up! I haven't touched this code in a long time but I have been wanting to revisit it for a while... just not gotten around to it since I graduated from college. Now that I know you're interested in getting this working I'll try to prioritize it. 

I've learned a lot about writing maintainable code since I wrote this haha.

**Comment by npjg** [comment]
Ideally this Media Station code would be re-architected to be more like https://github.com/npjg/tonka using some better design and some of the tooling I have developed for asset exports.

**Comment by npjg** [comment]
Also, for a bit more context (pun intended) on this project - this particular repo started as a prototype for creating a ScummVM engine for Media Station.

I haven't gotten around to that either, but that's my goal with all of these asset exporter projects I have (and I have several more that I haven't put on GitHub yet).

**Comment by n0samu** [comment]
Sounds great! I'm happy to hear that you're still interested in making improvements - and thanks for your work so far! 😄

**Comment by Puterboy1** [comment]
And make sure the sounds are exported at 22050hz, because I believe that is the native format for the sound files.

**Comment by n0samu** [comment]
Some context: Puterboy is the guy who asked me to rip these games' assets for him, which is how I ended up using your scripts and reporting these issues. So I'm sort of working with him on this. 🙂

**Comment by Puterboy1** [comment]
Only because they didn’t work for me….mostly.

**Comment by npjg** [comment]
Finally got around to the re-write that was needed here. Sorry this is so late, but if you're still interested in this project you can install the updated version from PyPI (https://pypi.org/project/MediaStation): `pip install MediaStation`. Then use the installed `MediaStation` script.

I have yet to address the sound question, but at least export should now work and be more maintainable.

**Comment by Puterboy1** [comment]
I am facing this installation problem:

C:\Users\jaker>python -m pip install C:\Users\jaker\Downloads\MediaStation-0.9.0-py3-none-any.whl
Processing c:\users\jaker\downloads\mediastation-0.9.0-py3-none-any.whl
Collecting self-documenting-struct>=0.9.1 (from MediaStation==0.9.0)
Using cached self_documenting_struct-0.9.1-py3-none-any.whl (7.3 kB)
INFO: pip is looking at multiple versions of mediastation to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement asset-extraction-framework>=0.9.2 (from mediastation) (from versions: 0.9.0, 0.9.1)
ERROR: No matching distribution found for asset-extraction-framework>=0.9.2

**Comment by Puterboy1** [comment]
I am facing this installation problem:
 
C:\Users\jaker>python -m pip install C:\Users\jaker\Downloads\MediaStation-0.9.0-py3-none-any.whl
Processing c:\users\jaker\downloads\mediastation-0.9.0-py3-none-any.whl
Collecting self-documenting-struct>=0.9.1 (from MediaStation==0.9.0)
  Using cached self_documenting_struct-0.9.1-py3-none-any.whl (7.3 kB)
INFO: pip is looking at multiple versions of mediastation to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement asset-extraction-framework>=0.9.2 (from mediastation) (from versions: 0.9.0, 0.9.1)
ERROR: No matching distribution found for asset-extraction-framework>=0.9.2

**Comment by Puterboy1** [comment]
You have to release 0.9.2.

**Comment by npjg** [comment]
Okay, now it should install for you. Sorry about that :(, yep I needed to release the new version.

**Comment by Puterboy1** [comment]
Thank you very much. I installed it, But now I need to know how to use it and where the installed file is.

**Comment by npjg** [comment]
Ah yes, the entry point should be installed by pip as `MediaStation` to a location on your path, and it can be invoked like `MediaStation ~/Desktop/Media\ Station/Pooh\ -\ English --export ~/Desktop/Pooh\ -\ English`.

**Comment by Puterboy1** [comment]
I think I found the .exe and thank you for the example of how to do it.

**Comment by npjg** [comment]
:) Sounds like you're on Windows. I have not tested on Windows (only on Linux), so there could be issues that come up due to that. Just let me know if so!

**Comment by Puterboy1** [comment]
N0Samu can give us an example.

**Comment by Puterboy1** [comment]
I also tried this: C:\Users\jaker>python C:\Users\jaker\AppData\Local\Programs\Python\Python311\Scripts\MediaStation.exe C:\Users\jaker\Downloads\DALMATIANS\DATA\INSTALL.CXT C:\Users\jaker\Downloads\DALMATIANS\DATA\Export
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\INSTALL.CXT
WARNING: No palette provided for this context.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Scripts\MediaStation.exe\__main__.py", line 7, in <module>
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Engine.py", line 70, in main
    media_station_engine.process(command_line_arguments.input, file_detection_entries)
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\asset_extraction_framework-0.9.2-py3.11.egg\asset_extraction_framework\Application.py", line 66, in process
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Context.py", line 208, in __init__
    self.read_asset_in_first_subfile()
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Context.py", line 379, in read_asset_in_first_subfile
    file, header = global_variables.application.get_asset_by_chunk_id(self.current_subfile.current_chunk.fourcc)
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

C:\Users\jaker>python C:\Users\jaker\AppData\Local\Programs\Python\Python311\Scripts\MediaStation.exe C:\Users\jaker\Downloads\DALMATIANS\DATA\ C:\Users\jaker\Downloads\DALMATIANS\DATA\Export
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\BOOT.STM
WARNING:root:Detected unknown section 0x000c
WARNING:root:Detected unknown section 0x0064
WARNING:root:Detected unknown section 0x0068
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\100.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\101.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\113.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\121.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\125.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\127.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\134.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\135.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\136.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\137.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\138.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\1385.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\139.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\140.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\1449.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\1463.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\154.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\163.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\171.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\173.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\175.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\177.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\180.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\183.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\186.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\188.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\190.CXT
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\1934.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\3680.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\439.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\INSTALL.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\PROFILE._ST
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Scripts\MediaStation.exe\__main__.py", line 7, in <module>
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Engine.py", line 70, in main
    media_station_engine.process(command_line_arguments.input, file_detection_entries)
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\asset_extraction_framework-0.9.2-py3.11.egg\asset_extraction_framework\Application.py", line 57, in process
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\asset_extraction_framework-0.9.2-py3.11.egg\asset_extraction_framework\Application.py", line 66, in process
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Profile.py", line 62, in __init__
    self.asset_declarations = ProfileSection(lines_in_file, AssetDeclaration)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Profile.py", line 111, in __init__
    entry = profile_entry_class(line)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Profile.py", line 197, in __init__
    self.asset_id: int = int(self._raw_entry[1])
                             ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by npjg** [comment]
For the first error, it cannot be run only on any `INSTALL.CXT` because no asset headers are present in the file; only asset data. All other CXTs must potentially be read to get all the headers. If you run it on a numbered CXT though (like a randomly chosen `230.cxt`, it should work on an individual one). Just not `INSTALL.CXT`.

**Comment by Puterboy1** [comment]
I ran it like this: C:\Users\jaker>python C:\Users\jaker\Downloads\Mediastation\MediaStation.exe C:\Users\jaker\Downloads\DALMATIANS\DATA\100.CXT C:\Users\jaker\Downloads\DALMATIANS\DATA\Export
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\100.CXT

**Comment by Puterboy1** [comment]
The processing was the result and then it stopped.

**Comment by npjg** [comment]
For the second error with `PROFILE._ST`, might be an issue with text encodings as I encountered that before too. Are you using Windows or Mac CD-ROM files? 

Anyway, workaround for now would be just removing `PROFILE._ST` from the folder. It is not actually needed to export assets, it can just add some nice things like asset names for titles that don't have them hard-coded (like this Dalmatians). But that is not currently implemented anyway; `PROFILE._ST` is just standalone currently.

**Comment by Puterboy1** [comment]
I am using Windows, I think.

**Comment by Puterboy1** [comment]
I removed Profile._ST but it is still like this:
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\101.CXT

**Comment by npjg** [comment]
So it just hangs there on the processing step?

**Comment by Puterboy1** [comment]
Yes. Seek n0samu. He might help us.

**Comment by Puterboy1** [comment]
I also tried it like this: C:\Users\jaker>python C:\Users\jaker\Downloads\Mediastation\MediaStation.exe C:\Users\jaker\Downloads\DALMATIANS\DATA\113.CXT C:\Users\jaker\Downloads\DALMATIANS\DATA
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\BOOT.STM
WARNING:root:Detected unknown section 0x000c
WARNING:root:Detected unknown section 0x0064
WARNING:root:Detected unknown section 0x0068
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\113.CXT
WARNING: No palette provided for this context.
Processing matched file C:\Users\jaker\Downloads\DALMATIANS\DATA\INSTALL.CXT
WARNING: No palette provided for this context.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jaker\Downloads\Mediastation\MediaStation.exe\__main__.py", line 7, in <module>
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Engine.py", line 70, in main
    media_station_engine.process(command_line_arguments.input, file_detection_entries)
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\asset_extraction_framework-0.9.2-py3.11.egg\asset_extraction_framework\Application.py", line 57, in process
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\asset_extraction_framework-0.9.2-py3.11.egg\asset_extraction_framework\Application.py", line 66, in process
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Context.py", line 208, in __init__
    self.read_asset_in_first_subfile()
  File "C:\Users\jaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\MediaStation\Context.py", line 379, in read_asset_in_first_subfile
    file, header = global_variables.application.get_asset_by_chunk_id(self.current_subfile.current_chunk.fourcc)
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by Puterboy1** [comment]
Have you tested it in Windows yet?

**Comment by npjg** [comment]
I just recently set up a Windows system for testing, but I have not tested yet. Has @n0samu been able to investigate on Windows at all?

**Comment by Puterboy1** [comment]
I’ll have to ask him.

**Comment by Puterboy1** [comment]
How is progress?

**Comment by npjg** [comment]
Sorry, life has really gotten in the way of me testing on Windows. I will try to do it soon.

**Comment by Puterboy1** [comment]
How soon?

**Comment by npjg** [comment]
Okay, sorry for the delay. I had a fresh Python v3.11 installation on Windows 10 and ran the version `MediaStation` published on pip.

I did not see any freezes when parsing both the PC or MAC versions of Dalmatians. So at present I cannot replicate the freeze you were seeing. Maybe you can give me an md5sum of the 101.CXT file so I can make sure we're looking at the same version?

**Comment by Puterboy1** [comment]
I could. Can we do this on Discord?

**Comment by npjg** [comment]
Yes I am npjg there too 😁 Will be looking for invite

**Comment by Puterboy1** [comment]
Here you go: https://discord.gg/U9SA4pE3kd
