### ISSUE TITLE
Is it possible for you to have the sounds ripped at 22050hz

### ISSUE THREAD

**Issue by Puterboy1** [npjg/MediaStation#3]
Because I believe that is the native format of the audio.

**Comment by n0samu** [comment]
Puterboy and I have been debating (on Discord) whether the audio files in the Pooh game are supposed to be 11025hz stereo or 22050hz mono. I think they're being ripped correctly as 11025hz stereo, but he thinks differently. It's pretty hard to tell the difference, but I analyzed the 2 audio channels by following [this SuperUser answer](https://superuser.com/questions/1218442/how-to-verify-whether-a-track-is-in-mono-or-stereo). 

Here is the ripped audio file I analyzed, along with the output of the phase-inverting process: [274.zip](https://github.com/npjg/cxt/files/10147858/274.zip). I think this result supports the idea that the audio is being ripped correctly as 11025hz stereo. It shows that there is a significant difference between the sound data in the 2 audio channels.

Anyway, I don't think a GitHub issue is necessarily the best place to have a discussion about this.

**Comment by Puterboy1** [comment]
I listened to the audio in Audacity and it sounds clearer at 22050hz.

**Comment by n0samu** [comment]
Does not change my conclusion.

**Comment by headsetguy37** [comment]
I am of the opinion that 22050Hz Mono is correct. 11025Hz Stereo sounds garbled.

**Comment by npjg** [comment]
By inspecting the executables more closely and talking to a former Media Station dev, I can finally confirm that indeed many if not all of these sounds are 22050Hz mono.
