### ISSUE TITLE
Extracting Barbi CD-ROM

### ISSUE THREAD

**Issue by ftp27** [npjg/MediaStation#6]
Hello. 
I'm trying to figure out how to extract "Magic Fairy Tales: Barbie As Rapunzel" and the script files on unknown section type: **0x0041** 

Here is result of processing: boot.stm
```
---
 Title Compiler T3.5r5 built Oct 11 1996 14:18:33 - 3.5r5
 Barbie
 Title Source J:\barbie.eng\src\rapunzel.imt; built Mon Jan 13 17:30:50 1997

WARNING:root:Detected unknown section 0x000c
WARNING:root:Detected unknown section 0x0064
WARNING:root:Detected unknown section 0x006a
---
```
I'm not sure what information a can share to define the issue. May be the source of iso: [Magic Fairy Tales: Barbie As Rapunzel](https://www.myabandonware.com/game/magic-fairy-tales-barbie-as-rapunzel-3mg)

**Comment by npjg** [comment]
Hmm, looks like there are indeed some issues with Barbie. I will try to look in a while.

**Comment by npjg** [comment]
Extraction for Barbie now seems to succeed with the latest release just published on PyPI, of course keep in mind keyframes for animations are not currently applied and some background sounds are not decoded properly - those are existing known issues.

**Comment by ftp27** [comment]
@npjg Thank you! It works like a charm. Now I'm going to figure out what to do with it...
